// Generated by scripts/generate-capture-fonts.mjs. Do not edit.
// Inter and JetBrains Mono, latin. Fetched when the export dialog first needs them and embedded
// in the captured scene as data URIs, so every renderer draws the same glyphs. See the script.
const FACES = [{"family":"Inter","weight":400,"file":"inter-latin-400.woff2"},{"family":"Inter","weight":700,"file":"inter-latin-700.woff2"},{"family":"JetBrains Mono","weight":400,"file":"jetbrains-mono-latin-400.woff2"},{"family":"JetBrains Mono","weight":600,"file":"jetbrains-mono-latin-600.woff2"}];

let css = '';

/** The @font-face rules, or '' until they have been fetched. Synchronous on purpose: the scene
 *  is built from a laid-out DOM and cannot wait. Callers await ensureCaptureFonts() first. */
export const captureFontCss = (): string => css;

/** Fetches the faces once. A failure is not fatal -- the export still happens, with whatever
 *  fonts the renderer has, which is exactly the old behaviour and better than no picture. */
export async function ensureCaptureFonts(): Promise<void> {
  if (css) return;
  try {
    const parts = await Promise.all(FACES.map(async (f) => {
      // Resolved against this MODULE, not the document.
      //
      // document.baseURI is the page, and this site is built with relative asset paths so it can
      // live under any prefix. From a model page at /models/<id>/ that asked the server for
      // /models/<id>/fonts/inter-latin-400.woff2 -- a 404, checked against the live site. The
      // fetch threw, css stayed empty, and every export made from a model page shipped with no
      // faces embedded: exactly the bug these fonts were added for, still there in the one place
      // exports are made. It only ever worked from the home page, which is where it was tried.
      //
      // The bundle puts this module under <base>/assets/ and the fonts under <base>/fonts/, so
      // ../fonts/ from here is right under any prefix and from any page that loads it.
      const r = await fetch(new URL(`../fonts/${f.file}`, import.meta.url).href);
      if (!r.ok) throw new Error(`${r.status} ${f.file}`);
      const b = new Uint8Array(await r.arrayBuffer());
      let s = '';
      for (let i = 0; i < b.length; i++) s += String.fromCharCode(b[i]);
      return `@font-face{font-family:"${f.family}";font-style:normal;font-weight:${f.weight};font-display:block;src:url(data:font/woff2;base64,${btoa(s)}) format("woff2")}`;
    }));
    css = parts.join('');
  } catch { css = ''; }
}
