// Generated by scripts/generate-capture-fonts.mjs. Do not edit.
// Inter and JetBrains Mono, latin. Fetched when the export dialog first needs them and embedded
// in the captured scene as data URIs, so every renderer draws the same glyphs. See the script.
const FACES = [{"family":"CaptureSans","weight":400,"file":"inter-latin-400.woff2"},{"family":"CaptureSans","weight":700,"file":"inter-latin-700.woff2"},{"family":"CaptureMono","weight":400,"file":"jetbrains-mono-latin-400.woff2"},{"family":"CaptureMono","weight":600,"file":"jetbrains-mono-latin-600.woff2"}];

let css = '';

/** The @font-face rules, or '' until they have been fetched. Synchronous on purpose: the scene
 *  is built from a laid-out DOM and cannot wait. Callers await ensureCaptureFonts() first. */
export const captureFontCss = (): string => css;

/** Fetches the faces once. A failure is not fatal -- the export still happens, with whatever
 *  fonts the renderer has, which is exactly the old behaviour and better than no picture. */
export async function ensureCaptureFonts(): Promise<void> {
  if (css) return;
  try {
    const parts = await Promise.all(FACES.map(async (f) => {
      const r = await fetch(new URL(`fonts/${f.file}`, document.baseURI).href);
      if (!r.ok) throw new Error(`${r.status} ${f.file}`);
      const b = new Uint8Array(await r.arrayBuffer());
      let s = '';
      for (let i = 0; i < b.length; i++) s += String.fromCharCode(b[i]);
      return `@font-face{font-family:"${f.family}";font-style:normal;font-weight:${f.weight};font-display:block;src:url(data:font/woff2;base64,${btoa(s)}) format("woff2")}`;
    }));
    css = parts.join('');
  } catch { css = ''; }
}
