import { writeFileSync } from 'node:fs';
import { createServer as createVite } from 'vite';
import { chromium } from 'playwright';
const id = process.argv[2] || 'parallax';
const vite = await createVite({ appType: 'mpa', logLevel: 'error', server: { port: 0, host: '127.0.0.1' } });
await vite.listen();
const base = vite.resolvedUrls.local[0].replace(/\/$/, '');
const browser = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 420, height: 340 }, deviceScaleFactor: 1 });
page.on('pageerror', (e) => console.log('page error:', e.message));
await page.goto(`${base}/embed/${id}/`);
await page.waitForTimeout(700);
const out = await page.evaluate(async () => {
  const { captureImage } = await import('/src/record.ts');
  const stage = document.querySelector('.stage');
  const blob = await captureImage(stage, { size: 340, backdrop: 'transparent', saveAspect: stage.offsetWidth / stage.offsetHeight });
  const bmp = await createImageBitmap(blob);
  const c = document.createElement('canvas'); c.width = bmp.width; c.height = bmp.height;
  const x = c.getContext('2d'); x.drawImage(bmp, 0, 0);
  const d = x.getImageData(0, 0, c.width, c.height).data; let a = 0; for (let i = 3; i < d.length; i += 4) if (d[i] > 8) a++;
  return { size: [bmp.width, bmp.height], alphaPct: +(100 * a / (d.length / 4)).toFixed(1), png: c.toDataURL('image/png') };
});
writeFileSync('qa/cap.png', Buffer.from(out.png.split(',')[1], 'base64'));
console.log(id, out.size, out.alphaPct + '% drawn -> qa/cap.png');
await browser.close();
await vite.close();
