/**
 * Prepare the release: everything the push is waiting for that a machine can do, then stop at the
 * sign-off, which is a person's.
 *
 *   node scripts/release-prepare.mjs        the same as Run → "Prepare the release" on the board
 *
 * It asks the board what the push needs -- the one answer the Run dialog shows under "What the
 * push needs" (scripts/jobs.mjs, whatIsNeeded, over the ledger's own verdict), kept in one place
 * rather than copied here -- and then does it: the gate steps that are not current, through
 * scripts/verify.mjs --step; the jobs that close a line (both renderers, the export matrix, the
 * snapshot); the two records a run regenerates, committed (docs/release-snapshot.json,
 * src/sitemap-dates.json); the ledger rebuilt; and asks again, up to three rounds. It stops at the
 * first thing that does not hold and says what, in the words of the run that found it.
 *
 * It never ticks the sign-off and never pushes. What it leaves open it names: the sign-off
 * (npm run signoff -- push, then commit docs/RELEASE-CHECKLIST.md last and git push), a document
 * to read against the change, a file of yours to commit. Those are a person's, and the point of
 * the list is that a person says them.
 *
 * Needs the board (npm run board). Without it there is nobody to ask, and it says so rather than
 * guessing. On 2026-09-30 this sequence was run twice by hand to take two releases to 51/51, and
 * the second stopped at 43/45 over a regenerated src/sitemap-dates.json nobody had committed.
 */
import { execFileSync, spawnSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { JOB } from './jobs.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const API = `http://127.0.0.1:${process.env.C3D_BOARD_PORT || 5178}/api`;
const ROUNDS = 3;
/** The records a run regenerates: committed here, with a message that says so. Anything else is yours. */
const RECORDS = ['docs/release-snapshot.json', 'src/sitemap-dates.json'];

const say = (s) => console.log(`${new Date().toISOString().slice(11, 19)}  ${s}`);
const git = (...a) => execFileSync('git', ['-c', 'core.quotepath=off', ...a], { cwd: ROOT, encoding: 'utf8' }).trim();
const run = (argv) => spawnSync(process.execPath, argv, { cwd: ROOT, stdio: 'inherit', env: { ...process.env, FORCE_COLOR: '0' } }).status ?? 1;
const stop = (why) => { say(`STOPPED: ${why}`); process.exit(1); };

async function needed() {
  let body;
  try { body = await (await fetch(`${API}/jobs`)).json(); } catch { return null; }
  return body.needed ?? null;
}
function verdict() {
  try {
    return JSON.parse(readFileSync(join(ROOT, 'docs', 'ledger.json'), 'utf8')).readiness.checklist.verdict.stages.before;
  } catch { return null; }
}

const first = await needed();
if (!first) stop(`the board is not answering at ${API}: start it (npm run board) and run this again, or press "Prepare the release" there`);

for (let round = 1; round <= ROUNDS; round++) {
  const n = await needed();
  if (!n) stop('the board stopped answering');
  const jobs = n.jobs.filter((j) => j !== 'live'); // the live check is after the push, not before it
  if (!n.open) { say('nothing is open before the push'); break; }
  if (!n.steps.length && !jobs.length) {
    say(`round ${round}: ${n.open} line(s) open, and no run closes them`);
    break;
  }
  say(`round ${round}: ${n.open} line(s) open; to run: ${[...n.steps.map((s) => `step ${s}`), ...jobs.map((j) => `job ${j}`)].join(', ')} (about ${n.minutes} min)`);
  if (n.steps.length) {
    say(`verify --step ${n.steps.join(',')}`);
    if (run(['scripts/verify.mjs', '--step', n.steps.join(',')]) !== 0) stop('a gate step did not hold: the lines marked FAILS above say which, and the board holds the detail per model');
  }
  for (const key of jobs) {
    const job = JOB.get(key);
    if (!job) stop(`the board asked for a job this list does not have: ${key}`);
    say(`job ${key}: ${job.name}`);
    if (run(job.argv) !== 0) stop(`${job.name} did not hold: its output above says why`);
  }
  // the records a run regenerates, committed; anything else uncommitted is a person's and stops this
  for (const file of RECORDS) {
    if (!git('status', '--porcelain', '--', file)) continue;
    git('add', '--', file);
    git('commit', '-q', '-m', file === RECORDS[0] ? 'The release snapshot, at the commit going out' : `${file}, regenerated by the build`);
    say(`committed ${file} (${git('rev-parse', '--short', 'HEAD')})`);
  }
  const dirty = git('status', '--porcelain').split('\n').filter(Boolean);
  if (dirty.length) stop(`uncommitted changes that are not a record a run regenerates: ${dirty.slice(0, 5).join('; ')}. Commit them, or leave them out and name them in the push notes`);
  say('rebuilding the ledger');
  run(['scripts/ledger.mjs']);
  await new Promise((r) => setTimeout(r, 3000));
}

const last = await needed();
const before = verdict();
say(`stage 1: ${before ? `${before.done}/${before.total}` : 'the ledger could not be read'}`);
for (const o of last?.other ?? []) say(`  ${o.kind === 'person' ? 'yours' : (o.kind ?? 'open')}: ${o.what}  (${String(o.item).slice(0, 70)})`);
const left = (last?.steps?.length ?? 0) + (last?.jobs?.filter((j) => j !== 'live').length ?? 0);
if (left) stop(`${left} run(s) are still needed after ${ROUNDS} rounds: ${[...(last.steps ?? []), ...(last.jobs ?? [])].join(', ')}`);
say(before && before.done === before.total
  ? 'everything before the push holds. What is left is yours: npm run signoff -- push, commit docs/RELEASE-CHECKLIST.md last, git push; then "After the push".'
  : 'nothing more a run can do; the lines above are a person\'s');
