/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 3e09a5b78b3be06ba8eb50ebc7856017)
interface __BaseEnv_Env {
	EXPORT_LIMIT: RateLimit;
	BROWSER: BrowserRun;
	ALLOWED_ORIGINS: "https://css3dlab.edgarasneverdauskas.com,https://evirtual.github.io";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS">> {}
}
