import type { Demo } from './types';

/** Batch C: 3D text effects and 3D form controls. */
export const demosC: Demo[] = [
  {
    id: 'flaptext',
    title: 'Split-flap board',
    description:
      'A departure board: each character is four half-height leaves, and a change drops the old top half and lands the new bottom half. JS only swaps the letters and restarts the CSS animation.',
    category: 'js',
    tags: ['text', 'loop', 'generated'],
    technique: ['two hinged half-leaves per cell', 'content: attr(data-c)', 'restart animation by re-adding a class', 'animation-fill-mode: both'],
  },
  {
    id: 'shadowtext',
    title: 'Isometric block text',
    description: 'One word stacked twenty times along the Z axis. Laid on a tilted floor, the copies merge into a solid extrusion under a gradient front.',
    category: 'css',
    tags: ['text', 'loop', 'layers'],
    technique: ['translateZ(calc(var(--i) * -1.2 * var(--u)))', 'rotateX + rotateZ floor', 'lightness from --i', 'background-clip: text'],
  },
  {
    id: 'wordcube',
    title: 'Rotating word prism',
    description: 'Four words on the four long sides of a prism that turns a quarter at a time, pausing on each. After 360° it is back where it started, so the loop has no seam.',
    category: 'css',
    tags: ['text', 'loop', 'shape'],
    technique: ['rotateX(n × -90deg) translateZ(h / 2)', 'hold + turn keyframes', 'backface-visibility: hidden', 'per-keyframe easing'],
  },
  {
    id: 'foldtext',
    title: 'Z-fold headline',
    description: 'A headline printed across three panels folded like a brochure. Each panel is a window onto the same wide sheet; hover or focus flattens the paper.',
    category: 'css',
    tags: ['text', 'hover', 'paper'],
    technique: ['nested hinges with transform-origin', 'same sheet offset by --i × -100%', 'clip the leaf, never the hinge', 'shading faded with opacity'],
  },
  {
    id: 'crawl',
    title: 'Opening crawl',
    description: 'Paragraphs scroll away on a plane tipped back 55°. The fade into the distance is an overlay on top, because a mask on a 3D ancestor would flatten the scene.',
    category: 'css',
    tags: ['text', 'loop', 'scene'],
    technique: ['perspective-origin at the bottom edge', 'rotateX(55deg) hinged on the bottom', 'translateY loop, two copies half a loop apart', 'gradient overlay instead of mask'],
  },
  {
    id: 'anaglyph',
    title: 'Anaglyph 3D text',
    description: 'A red and a cyan copy of one word, blended with screen. The pointer sets how far apart they sit and turns the card, like old red/cyan cinema glasses.',
    category: 'js',
    tags: ['text', 'pointer', 'blend'],
    technique: ['mix-blend-mode: screen on the leaves', 'pointer → --sx / --ry / --rx', 'flat card, no preserve-3d around a blend', 'fast transition live, springy on release'],
  },
  {
    id: 'check',
    title: '3D checkboxes',
    description: 'Each checkbox is a small glass cube with the tick on its bottom face. :checked rolls the cube a quarter turn forward; the inputs are real, so keyboard and forms just work.',
    category: 'css',
    tags: ['controls', 'form-hack', 'shape'],
    technique: ['input:checked + label', 'cube rolls rotateX(90deg)', 'static label = hit target', 'strike-through with scaleX'],
  },
  {
    id: 'tabs',
    title: 'Prism tabs',
    description: 'The tab panels are the four long sides of a prism. Radio inputs and labels pick a tab; each one sets a step count and the prism turns to that face.',
    category: 'css',
    tags: ['controls', 'form-hack', 'shape'],
    technique: ['radio:checked ~ sibling', '--step × 90deg', 'translateZ(-h / 2) keeps the front at z = 0', 'backface-visibility: hidden'],
  },
  {
    id: 'radial',
    title: 'Radial action menu',
    description: 'A floating action button built from a checkbox and its label. Closed, it is only the + button; checked, its five actions walk out along their spokes into a ring round it, coming forward one after another.',
    category: 'css',
    tags: ['controls', 'form-hack', 'menu', 'expands'],
    technique: ['rotate(a) translateX(r) rotate(-a)', 'matching transform lists animate per function', 'transition-delay from --i', 'checkbox + label toggle'],
  },
  {
    id: 'magnet',
    title: 'Magnetic button',
    description: 'Inside its field the button shifts and leans toward the pointer while its label floats higher, so the two slide apart. JS only reports the pointer position; release it and a springy transition takes it home.',
    category: 'js',
    tags: ['controls', 'pointer', 'button'],
    technique: ['pointer → --mx / --my', 'translate3d + rotate from the same two numbers', 'label at translateZ for parallax', 'overshoot easing as a spring'],
  },
];
