import type { Demo } from './types';

/** Second batch of zero-JavaScript demos. */
export const pureDemos2: Demo[] = [
  {
    id: 'pyramid',
    title: 'Pyramid',
    description: 'A glass pyramid with a glowing core: triangles cut with clip-path, leaned inward by exactly the angle that makes the tips meet.',
    category: 'css',
    tags: ['loop', 'shape'],
    technique: ['clip-path: polygon()', 'transform-origin: bottom', 'lean angle = asin((base / 2) / slant)'],
  },
  {
    id: 'cylinder',
    title: 'Cylinder',
    description: 'A glass tube with rings of light rising inside. CSS has no curves in 3D, so the tube is 24 flat strips, each 2r × tan(180° / 24) wide.',
    category: 'css',
    tags: ['loop', 'shape'],
    technique: ['strip width = 2r × tan(180° / n)', 'rotateY + translateZ', 'per-strip shading'],
  },
  {
    id: 'coin',
    title: 'Spinning coin',
    description: 'Two faces and a band of 24 slats round the edge between them, so it is solid even edge-on.',
    category: 'css',
    tags: ['loop', 'shape'],
    technique: ['a rim of rotateZ + translateY slats', 'backface-visibility', 'rotateY spin'],
  },
  {
    id: 'globe',
    title: 'Wireframe globe',
    description: 'Nine circles rotated around the Y axis make the meridians; one laid flat is the equator.',
    category: 'css',
    tags: ['loop', 'shape'],
    technique: ['border-radius: 50% rings', 'rotateY(i × 20deg)', 'preserve-3d spin'],
  },
  {
    id: 'gyro',
    title: 'Gyroscope',
    description: 'Three nested rings, each spinning on a different axis — the rotations compound.',
    category: 'css',
    tags: ['loop', 'loader'],
    technique: ['nested preserve-3d', 'one axis per level', 'different durations'],
  },
  {
    id: 'flipper',
    title: 'Flipping loader',
    description: 'The classic square loader: half a turn on X, then half a turn on Y.',
    category: 'css',
    tags: ['loop', 'loader'],
    technique: ['perspective() inside transform', 'multi-step @keyframes', 'no wrapper needed'],
  },
  {
    id: 'tunnel',
    title: 'Infinite tunnel',
    description: 'Identical frames fly from far away to past the camera on staggered negative delays.',
    category: 'css',
    tags: ['loop'],
    technique: ['animated translateZ', 'negative animation-delay', 'opacity fade-in at distance'],
  },
  {
    id: 'starfield',
    title: 'Warp starfield',
    description: 'Each layer is ONE element; its stars are box-shadows of it, written out as one list.',
    category: 'css',
    tags: ['loop', 'generated'],
    technique: ['box-shadow as particles', 'star offsets in em: one em = one unit', 'translateZ fly-through'],
  },
  {
    id: 'waveletters',
    title: 'Letter wave',
    description: 'Every letter does the same flip; the stagger turns it into a wave.',
    category: 'css',
    tags: ['loop', 'text'],
    technique: ['inline-block letters', 'animation-delay from --i', 'rotateY flip'],
  },
  {
    id: 'textring',
    title: 'Text ring',
    description: 'A word wrapped around a ring, one character per slice, standing on a rim you can see all the way round.',
    category: 'css',
    tags: ['loop', 'text'],
    technique: ['rotateY(i × 360° / n) translateZ(r)', 'backface-visibility: hidden', 'monospace for even spacing', 'a rotateX(90deg) rim for the far side'],
  },
  {
    id: 'layertext',
    title: 'Layered text',
    description: 'Real depth this time: ten copies of GO DEEP stacked along Z, so perspective is correct.',
    category: 'css',
    tags: ['loop', 'text'],
    technique: ['stacked copies with translateZ', 'aria-hidden duplicates', 'compare with the shadow version'],
  },
  {
    id: 'sign',
    title: 'Hanging sign',
    description: 'A pendulum is just rotateX around the top edge with an ease-in-out alternate.',
    category: 'css',
    tags: ['loop'],
    technique: ['transform-origin: top', 'animation-direction: alternate', 'ease-in-out = pendulum'],
  },
  {
    id: 'laptop',
    title: 'Laptop lid',
    description: 'The lid hinges on the back edge. Its two sides are separate faces: shell and screen.',
    category: 'css',
    tags: ['loop'],
    technique: ['floor plane via rotateX + rotateZ', 'transform-origin: top', 'two-sided element with backface-visibility'],
  },
  {
    id: 'cardfan',
    title: 'Card fan',
    description: 'Five cards share one pivot below the hand and fan out by index.',
    category: 'css',
    tags: ['loop'],
    technique: ['transform-origin far below the card', 'rotateZ(var(--i) × step)', 'translateZ per card to avoid z-fighting'],
  },
  {
    id: 'door',
    title: 'Door',
    description: 'Hover or focus to open. The light behind is just the frame’s background.',
    category: 'css',
    tags: ['hover'],
    technique: ['transform-origin: left', 'transition on :hover / :focus', 'perspective-origin'],
  },
  {
    id: 'explode',
    title: 'Exploding cube',
    description: 'Hover to blow the faces apart. One custom property moves all six.',
    category: 'css',
    tags: ['hover', 'shape'],
    technique: ['translateZ(var(--d))', 'transition on a var()-driven transform', 'spin continues underneath'],
  },
  {
    id: 'isotiles',
    title: 'Hover tiles',
    description: 'Sweep across the floor. Tiles rise instantly and sink slowly, leaving a trail.',
    category: 'css',
    tags: ['hover'],
    technique: ['hit-testing works in 3D', 'fast transition in, slow transition out', 'isometric floor'],
  },
  {
    id: 'zones',
    title: 'No-JS tilt',
    description: 'Pointer-following tilt without JavaScript: nine invisible hover zones steer the card.',
    category: 'css',
    tags: ['hover'],
    technique: ['3 × 3 grid of hover zones', ':hover ~ sibling selector', 'pointer-events: none on the card'],
  },
  {
    id: 'rollbutton',
    title: 'Rolling button',
    description: 'The button is a bar with two faces; hover rolls the second one into view.',
    category: 'css',
    tags: ['hover', 'ui'],
    technique: ['static hit target, moving child', 'two faces 90° apart', 'translateZ(-h/2) keeps it in place'],
  },
  {
    id: 'switch',
    title: 'Rocker switch',
    description: 'A real checkbox underneath: click, tap or press Space. The rocker tips on :checked.',
    category: 'css',
    tags: ['form-hack', 'ui', 'controls'],
    technique: ['input:checked + sibling', 'rotateX rocker', 'label makes the whole thing clickable'],
  },
  {
    id: 'dropdown',
    title: 'Fold-down menu',
    description: 'Hover or focus the button: items swing down from their top edge, one after another.',
    category: 'css',
    tags: ['hover', 'ui'],
    technique: ['rotateX(-50deg) → 0 with origin top', 'transition-delay from --i', 'tabindex + :focus for keyboards'],
  },
];
