import type { Demo } from './types';

/** Demos that run with zero JavaScript — HTML and CSS only. */
export const pureDemos: Demo[] = [
  {
    id: 'cube',
    title: 'Rotating cube',
    description: 'Six faces placed with rotate + translateZ, spun by a single keyframe animation.',
    category: 'css',
    tags: ['loop'],
    technique: ['transform-style: preserve-3d', 'perspective', '@keyframes', ':nth-child places each face'],
  },
  {
    id: 'flip',
    title: 'Flip card',
    description: 'Hover, tap or focus to flip. The back face is hidden until it turns toward you.',
    category: 'css',
    tags: ['hover'],
    technique: ['backface-visibility: hidden', 'transition', ':hover / :focus-visible'],
  },
  {
    id: 'carousel',
    title: 'Ring carousel',
    description: 'Panels arranged on a circle. The radius comes from tan(): (width / 2) / tan(180° / count).',
    category: 'css',
    tags: ['loop'],
    technique: ['preserve-3d', 'rotateY + translateZ', 'radius = (width / 2) / tan(180° / n)'],
  },
  {
    id: 'text',
    title: 'Extruded text',
    description: 'A stack of hard text-shadows, each one step further and a little darker, reads as solid depth.',
    category: 'css',
    tags: ['text', 'faux-3d', 'loop'],
    technique: ['text-shadow stack', 'darker layer per step', 'rotateY rocking'],
  },
  {
    id: 'layers',
    title: 'Exploded layers',
    description: 'Isometric plates that rest spread apart along the Z axis and close up together, each placed by one custom property.',
    category: 'css',
    tags: ['loop'],
    technique: ['rotateX + rotateZ isometric view', 'translateZ', 'var() in the resting pose, one keyframe to close'],
  },
  {
    id: 'button',
    title: 'Push button',
    description: 'Press it. The edge is a generated box-shadow stack that collapses on :active.',
    category: 'css',
    tags: ['controls', 'faux-3d'],
    technique: ['box-shadow stack', ':active on a static hit target', 'rotateX tilt'],
  },
  {
    id: 'fold',
    title: 'Folding map',
    description: 'Nested panels, each hinged on its parent’s edge, folding up like a paper map.',
    category: 'css',
    tags: ['loop'],
    technique: ['nested preserve-3d', 'transform-origin: left', 'alternating keyframes'],
  },
  {
    id: 'orbit',
    title: 'Atom orbits',
    description: 'Three rings tilted into different planes, each spinning inside its own plane.',
    category: 'css',
    tags: ['loop'],
    technique: ['preserve-3d', 'static tilt wrapper + spinning child', 'own tilt and duration per ring'],
  },
  {
    id: 'bars',
    title: '3D bar chart',
    description: 'Each bar is a real cuboid — front, side and top face — growing on a staggered delay.',
    category: 'css',
    tags: ['loop'],
    technique: ['preserve-3d inside flexbox', 'scaleY walls + translateY lid (no layout)', 'animation-delay stagger'],
  },
  {
    id: 'book',
    title: 'Opening book',
    description: 'Cover and pages hinge on the spine, each opening to a slightly different angle.',
    category: 'css',
    tags: ['loop'],
    technique: ['transform-origin: left', 'var() end angle per sheet', 'one @property --open, a staggered slice per sheet'],
  },
  {
    id: 'radio',
    title: 'Radio-button cube',
    description: 'Interactive with no JavaScript: checked radios steer the cube through sibling selectors.',
    category: 'css',
    tags: ['form-hack', 'controls'],
    technique: [':checked ~ sibling selector', 'transition on transform', '<label for> as the button'],
  },
  {
    id: 'grid',
    title: 'Synthwave floor',
    description: 'A gradient-drawn grid laid flat with rotateX, scrolling toward you forever.',
    category: 'css',
    tags: ['loop'],
    technique: ['perspective on parent', 'rotateX floor plane', 'line layer slid with transform (not background-position)'],
  },
  {
    id: 'helix',
    title: 'DNA helix',
    description: 'Rungs spin on negative delays; dots counter-rotate so they always face the camera.',
    category: 'css',
    tags: ['loop'],
    technique: ['negative animation-delay', 'billboard counter-rotation', 'delay from --i per rung'],
  },
  {
    id: 'tiles',
    title: 'Tile wave',
    description: 'A 4×4 grid of two-sided tiles flipping in a diagonal wave.',
    category: 'css',
    tags: ['loop'],
    technique: ['backface-visibility', 'delay = (row + column) × step', '--d per tile in its style'],
  },
];
